#!/usr/bin/env bash
# =============================================================================
# package.sh — freeze RaggyEditor into a standalone executable.
#
#   macOS   -> dist/RaggyEditor.app   (double-clickable)
#   Windows -> dist/RaggyEditor/RaggyEditor.exe
#   Linux   -> dist/RaggyEditor/RaggyEditor
#
# The model is NOT bundled: it is downloaded on first use, which is what keeps
# the artifact small. The app works offline before that (LSA fallback).
#
# Usage:
#   ./run.sh package            # build for the current OS
#   ./run.sh package --dmg      # macOS: also produce a .dmg
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PY="$ROOT/.venv/bin/python"
[ -x "$PY" ] || { echo "✗ no .venv. Run: ./run.sh install"; exit 1; }

MAKE_DMG=0
for a in "$@"; do [ "$a" = "--dmg" ] && MAKE_DMG=1; done

echo "== PACKAGE — freezing RaggyEditor =="

if ! "$PY" -c "import PyInstaller" 2>/dev/null; then
  echo "  installing PyInstaller…"
  uv pip install --python "$PY" pyinstaller >/dev/null
fi

echo "  cleaning previous build…"
rm -rf "$ROOT/build" "$ROOT/dist"

# ---------------------------------------------------------------------------
# Stamp the build. ⚠️ A bundle that cannot say which code it contains is not
# checkable, and that is how a stale .app got shipped and run: the fix was
# committed, the bundle was not rebuilt, and every symptom looked like "the fix
# did not work". The stamp is baked in as a generated module.
# ---------------------------------------------------------------------------
STAMP="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown) · $(date -u '+%Y-%m-%d %H:%M UTC')"
echo "  build stamp: $STAMP"
cat > "$ROOT/src/raggy/_build.py" <<STAMP_EOF
"""Generated by scripts/package.sh. Do not edit; do not commit."""

STAMP = "$STAMP"
STAMP_EOF

echo "  running PyInstaller (this takes a few minutes)…"
"$PY" -m PyInstaller --noconfirm --clean \
  --distpath "$ROOT/dist" --workpath "$ROOT/build" \
  "$ROOT/packaging/raggyeditor.spec"

# ---------------------------------------------------------------------------
# Verify the bundle actually RUNS. A build that produces a file is not the same
# as a build that produces a working app; the selftest constructs the window
# and exits, which catches missing Qt plugins and absent compiled modules.
# ---------------------------------------------------------------------------
case "$(uname -s)" in
  Darwin) BIN="$ROOT/dist/RaggyEditor.app/Contents/MacOS/RaggyEditor" ;;
  *)      BIN="$ROOT/dist/RaggyEditor/RaggyEditor" ;;
esac

if [ -x "$BIN" ]; then
  echo "  verifying the bundle runs…"
  # ⚠️ The output is SHOWN, not swallowed: it names the build and reports the
  # chunker's maximum chunk size, which is how a stale bundle announces itself.
  if SELFTEST_OUT="$(QT_QPA_PLATFORM=offscreen "$BIN" --selftest 2>&1)"; then
    echo "$SELFTEST_OUT" | sed 's/^/    /'
    echo "  ✓ selftest passed"
  else
    echo "$SELFTEST_OUT" | sed 's/^/    /'
    echo "  ⚠️ selftest FAILED — the bundle was produced but does not behave."
    echo "     If the chunk size above exceeds its target, this bundle was built"
    echo "     from older code than the working tree."
    exit 1
  fi
else
  echo "  ⚠️ could not find the built binary at $BIN"
  exit 1
fi

SIZE="$(du -sh "$ROOT/dist" | cut -f1)"
echo "  ✓ built: $ROOT/dist  ($SIZE)"

# ---------------------------------------------------------------------------
# macOS: a .dmg is the thing a user actually downloads.
# ---------------------------------------------------------------------------
if [ "$(uname -s)" = "Darwin" ] && [ "$MAKE_DMG" = "1" ]; then
  echo "  creating DMG…"
  DMG="$ROOT/dist/RaggyEditor.dmg"
  rm -f "$DMG"
  hdiutil create -volname "RaggyEditor" -srcfolder "$ROOT/dist/RaggyEditor.app" \
    -ov -format UDZO "$DMG" >/dev/null
  echo "  ✓ $DMG ($(du -sh "$DMG" | cut -f1))"
  echo "  ⚠️ unsigned: macOS Gatekeeper will warn until you codesign + notarise"
  echo "     (see README → Shipping). testers can right-click → Open once."
fi

echo
echo "  Note: the app works immediately. The language model that enables search by"
echo "  meaning is offered once, in-app, when a search finds no exact match — or"
echo "  on demand from Help ▸ Enable Search by Meaning…"
